CB-296: `init_postgres` function in `manage.py` doesn't work for the development environment
metabrainz/critiquebrainz pull request #308
Opened 2020-09-23 14:38 UTC by amCap1712

I was unable to find where this is done in the Docker but according to the comment on the ticket this fix seemed right.

2020-09-24 08:13 UTC, alastair approved these changes
Perfect, thanks.

The database is automatically initialized with docker based on these environment variables: https://github.com/metabrainz/critiquebrainz/blob/dd20a4125010b81744ad9f2182daa84ec869c024/docker/docker-compose.dev.yml#L11-L14

2020-09-24 08:20 UTC, amCap1712 commented
Ok! Understood now. Thanks

2020-09-25 12:50 UTC, alastair requested changes

2020-09-25 12:50 UTC, alastair commented on manage.py
>          create_extension(db_uri)
I just noticed that we also create the extension with this entrypoint mount:
https://github.com/metabrainz/critiquebrainz/blob/master/docker/docker-compose.dev.yml#L18

This means that we can also remove `create_extension` and `skip_create_db`

2020-09-25 13:01 UTC, alastair commented on manage.py
>          create_extension(db_uri)
check for uses in the code of `--skip-create-db`, there are some in the test scripts, and also in the documentation

2020-09-25 14:25 UTC, alastair approved these changes

2020-09-25 14:25 UTC, merged