Include more data in the reviews endpoint
metabrainz/critiquebrainz pull request #441
Opened 2022-07-07 12:57 UTC by anshg1214

* Return average ratings for entity if the entity_id is given
* Add parameter to include the metadata for the entities

2022-07-15 15:36 UTC, alastair requested changes

2022-07-15 15:47 UTC, anshg1214 commented on critiquebrainz/ws/review/views.py
> +    if False:
I've already fixed this in the previous commit :)

2022-07-15 15:49 UTC, anshg1214 commented on critiquebrainz/ws/review/views.py
> +    if entity_id:
Done 👍

2022-07-15 15:51 UTC, anshg1214 commented on critiquebrainz/ws/review/views.py
> +        return jsonify(limit=limit, offset=offset, count=count, reviews=reviews, avg_rating=avg_rating)
Done 👍

2022-07-29 16:05 UTC, alastair approved these changes
looks good now, thanks for fixing the last few issues!

2022-07-29 16:06 UTC, merged