Adding Guidelines and link to CoC
metabrainz/critiquebrainz pull request #442
Opened 2022-07-10 06:51 UTC by Aerozol

Discussed at length on IRC, feedback welcome.

2022-07-13 05:04 UTC, anshg1214 requested changes

2022-07-13 05:04 UTC, anshg1214 commented on critiquebrainz/frontend/templates/index/about.html
> +  {{ _('Content has to be a 'review' or a otherwise genuine reflection on the entity.
```suggestion
  {{ _('Content has to be a \'review\' or a otherwise genuine reflection on the entity.
```

2022-07-13 05:04 UTC, anshg1214 commented on critiquebrainz/frontend/templates/index/about.html
> + If you're not sure if you are allowed to post it, don't.') }}
```suggestion
 If you\'re not sure if you are allowed to post it, don\'t.') }}
```

2022-07-14 04:42 UTC, anshg1214 approved these changes
Thanks!

2022-07-25 09:14 UTC, alastair approved these changes
🙌  thank you @Aerozol! 🎉

2022-07-25 09:15 UTC, merged