Change socket to http in uwsgi.ini
metabrainz/critiquebrainz pull request #502
Opened 2023-11-02 11:31 UTC by MonkeyDo

We are trying to resolve issues with uWSGI running in the CB docker containers, which fail with the error `bind(): Address already in use [core/socket.c line 769]`
See this discussion or some background: https://chatlogs.metabrainz.org/libera/metabrainz/2023-11-02/?msg=5243055&page=2

This mimics how we configure the artwork redirect container: https://github.com/metabrainz/artwork-redirect/blob/c632ecfda1c5d5037e20a341f992b35ea7cc5ab8/docker/prod/uwsgi.ini#L3

2023-11-02 11:36 UTC, zas approved these changes

2023-11-02 11:38 UTC, MonkeyDo commented
I am building a docker image from this branch so i can deploy it to the beta CB container.
If everything is working fine and in the coming days/weeks the container is still stable while the untouched prod container fails, then we can merge this PR

2023-11-02 15:16 UTC, zas requested changes
Actually this doesn't work without changes to gateways config.
Plus it might not be the actual issue.

2023-11-21 19:40 UTC, amCap1712 approved these changes

2023-11-21 19:40 UTC, merged

2023-11-22 11:11 UTC, MonkeyDo commented
Thanks @amCap1712 !